### ISSUE TITLE
Adding animation on home page 

### ISSUE THREAD

**Issue by marcellinuselbert** [ristekoss/ristek-link#4]
### Current Home Page

Ristek link home page is not animated 

![RISTEK-LINK](https://user-images.githubusercontent.com/51221428/137615900-2dcf1f79-7d00-41e8-9dff-7cc66d165585.JPG)

### Requested Home Page

Ristek link home page is animated fade in the left and right banner, product hunt logo, ristek link subtext, slide-in the input and text expand the ristek.link main text. 

In my opinion, using animation will increase the quality of the user interface much more, attract user attention more, also better impression on the user

https://user-images.githubusercontent.com/51221428/137616575-1928eff4-ceeb-40f2-91b0-23d7e749000c.mov

**Comment by jonathanfilbert** [comment]
![8C977DAA-8123-4840-84F6-065A30FD9A4B](https://user-images.githubusercontent.com/30317542/137617823-033e7dfb-91dc-4540-92df-72c4b6a88c09.jpeg)

Since our vp of design has approved the animation, I’d say LGTM. Please make a PR, nice job 👍🚀

**Comment by jonathanfilbert** [comment]
In progress #5
